  name: Build feeds
  on:
    push:
      branches:
        - main
    schedule:
      - cron:  '0 0 * * *'
  jobs:
    build-feed-page:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build feeds
        run: cat feed-sites | node index.js > feeds.md
      - uses: stefanzweifel/git-auto-commit-action@v5



